language: java

dist: trusty
sudo: false

- wget https://github.com/sormuras/bach/raw/master/install-jdk.sh

matrix:
  include:
  - env: JDK='Oracle JDK 10'
      install: . ./install-jdk.sh -F 10 -L BCL
  - env: JDK='OpenJDK 10'
      install: . ./install-jdk.sh -F 10 -L GPL
   script:
   - ./gradlew --version
   - ./gradlew test
  
jdk: oraclejdk10

./mvnw install -DskipTests=true -Dmaven.javadoc.skip=true -B -V

install: true
script: ./mvnw clean install


cache:
  directories:
  - $HOME/.m2

script:
  - ./mvnw clean install
  - bash <(curl -s https://codecov.io/bash)
 
